version: "3.7"
services:
    wordpress:
        image: wordpress:latest
        container_name: wordpress
        depends_on:
            - database
        environment:
            WORDPRESS_DB_HOST: database:3306
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: wordpress
        volumes:
            - ./wp-content:/var/www/html/wp-content
        ports:
            - "8080:80"
    
    database:
        image: mariadb:latest
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: root
            MYSQL_PASSWORD: wordpress
        volumes:
            - ./db:/var/lib/mysql
    
    nginx:
        image: nginx:latest
        container_name: nginx
        depends_on:
            - wordpress
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/nginx/certs
        ports:
          - "443:443"
          - "80:80"